type User {
	UUID: String
	Name: String
	Posts: [Post]
}

type Post {
	UUID: String
	Text: String
}

input UserInput {
	Name: String
	Posts: [PostInput]
}

input PostInput{
	Text: String
}

type Mutation {
	postgresCreateUser(input: UserInput!): User
	proxyCreateUser(input: UserInput!): User
	auroraCreateUser(input: UserInput!): User
}

type Query {
	postgresGetUser(uuid: String!): User
	proxyGetUser(uuid: String!): User
	auroraGetUser(uuid: String!): User
}

schema {
	query: Query
	mutation: Mutation
}